In [1]:
import pickle
import numpy as np

In [2]:
ohe_sex = pickle.load(open('Models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('Models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('Models/clf.pkl','rb'))


In [9]:
#Assume user input 
# Pclass , gender , age , sibSp , Parch , fare , embarked
test_input = np.array([2 , 'female' , 31.0 , 0 , 0 , 10.5 , 'S' ], dtype=object).reshape(1,7)

In [10]:
test_input

array([[2, 'female', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [11]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

c:\Users\gaurav gupta\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [12]:
test_input_sex

array([[1., 0.]])

In [13]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [14]:
test_input_embarked

array([[0., 0., 1.]])

In [15]:
test_input_age = test_input[:,2].reshape(1,1)

In [16]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked) , axis=1)

In [19]:
test_input_transformed

array([[2, 0, 0, 10.5, 31.0, 1.0, 0.0, 0.0, 0.0, 1.0]], dtype=object)

In [20]:
clf.predict(test_input_transformed)

array([1])